class UserNotFoundError(Exception):
    pass


class SignupFailedException(Exception):
    pass
